version: '3.9'

services:
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: safal
      POSTGRES_PASSWORD: safal123
      POSTGRES_DB: safaldb
    volumes:
      - safalVolume:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  safalVolume: